name: Generate Political News Report

on:
  schedule:
    # Runs at 00:00, 08:00, and 16:00 UTC (every 8 hours)
    - cron: '0 */8 * * *'
    
    # Alternative: Specific times (6am, 2pm, 10pm UTC)
    # - cron: '0 6,14,22 * * *'
    
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci  # Uses package-lock.json for faster, reliable installs
      
      - name: Run news aggregation script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional: Override other config via environment variables
          # GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: node generate-report.js  # Adjust filename if needed
      
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: news-report-${{ github.run_number }}
          path: |
            public/index.html
            public/data.json
            public/logs.json
          retention-days: 7
      
      # Optional: Auto-commit generated files back to repository
      - name: Commit and push changes
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update news report [skip ci]"
          git push
